=== fastquant/ctpdemo/spec/ftd.1.dtd
<?xml version="1.0" encoding="GB2312"?>
    <!--
        中国证券交易标准 期货交易传输协议标准1.0(Securities Exchange Protocol 1.0)描述用DTD
    -->
    <!ELEMENT ftd (packages, tids, fields, items, types)>
    <!--
        ftd中包含下列内容
            packages    所有报文的定义
            tids        所有的报文编号的定义
            fields      所有域的定义
            items       所有字段的定义
            types       所有衍生类型的定义
    -->
    <!ELEMENT packages (packageDefine*)>
    <!--
        packages中是一组packageDefine
    -->
    <!ELEMENT packageDefine (field*)>
    <!ATTLIST packageDefine
        name    NMTOKEN                         #REQUIRED
        tid     NMTOKEN                         #REQUIRED
        model   (none|dialog|private|market)    #REQUIRED
        comment CDATA                           #IMPLIED
    >
    <!--
        每个packageDefine中可以定义下列属性
            name       报文名称, 在packages中唯一
            tid        报文编号, 应该出现在tids中的tidDefine中的name中
            comment    报文说明
        在每个packageDefine中, 需要用field说明包含的所有域的使用
    -->
    <!ELEMENT field EMPTY>
    <!ATTLIST field
            name     NMTOKEN    #REQUIRED
            maxOccur CDATA      #REQUIRED
            minOccur CDATA      #REQUIRED
            comment  CDATA      #IMPLIED
    >
    <!--
        在报文定义中使用的域不需要给出详细说明,仅仅是对fields中定义的域的引用。
        每个field中可以定义下列属性
            name        域名称, 应该出现在fields中的fieldDefine中的name中
            maxOccur    报文中该域最多出现次数, 应当是整数,或者用*表示任意多个
            minOccur    报文中该域最少出现次数, 应当是整数
            comment     在此报文中使用该域的说明(不是域本身的说明)
    -->
    <!ELEMENT tids (tidDefine*)>
    <!--
        tids中是一组tidDefine
    -->
    <!ELEMENT tidDefine EMPTY>
    <!ATTLIST tidDefine
            name  NMTOKEN    #REQUIRED
            value NMTOKEN    #REQUIRED
    >
    <!--
        每个报文编号定义tidDefine中可以定义下列属性
            name     编号名称, 在tids中唯一
            value    编号的值, 应当是一个整数
    -->
    <!ELEMENT fields (fieldDefine*)>
    <!--
        fields中是一组fieldDefine
    -->
    <!ELEMENT fieldDefine (item*)>
    <!ATTLIST fieldDefine
        name     NMTOKEN    #REQUIRED
        fid      NMTOKEN    #REQUIRED
        fidValue NMTOKEN    #REQUIRED
        comment  CDATA      #IMPLIED
    >
    <!--
        每个域定义fieldDefine中可以定义下列属性
            name        域的名称, 在fields中唯一
            fid         域编号
            fidValue    域编号的值, 应当是一个整数
            comment     域说明
        在每个fieldDefine中, 需要说明包含的字段item的使用
    -->
    <!ELEMENT item EMPTY>
    <!ATTLIST item
        name    NMTOKEN    #REQUIRED
        comment CDATA      #IMPLIED
    >
    <!--
        在域中使用的字段不需要给出详细说明, 仅仅是对items中定义的字段的引用
        每个item中可以定义下列属性
            name       字段名称, 应该出现在items中的itemDefine中的name中
            comment    在此域中使用该字段的说明(不是字段本身的说明)
    -->
    <!ELEMENT items (itemDefine*)>
    <!--
        items中是一组itemDefine
    -->
    <!ELEMENT itemDefine EMPTY>
    <!ATTLIST itemDefine
        name       NMTOKEN    #REQUIRED
        type       CDATA      #REQUIRED
        comment    CDATA      #IMPLIED
    >
    <!--
        每个字段定义 itemDefine 中可以定义下列属性
        name       字段的名称, 在items中唯一
        type       字段类型, 应该是基本类型, 或者出现在types中的typeDefine中的name中
        comment    字段说明
    -->
    <!ELEMENT types (typeDefine*)>
    <!--
        types中是一组typeDefine
    -->
    <!ELEMENT typeDefine (enumValue*)>
    <!ATTLIST typeDefine
        name         NMTOKEN   #REQUIRED
        baseType     CDATA     #REQUIRED
        length       CDATA     #IMPLIED
        precision    CDATA     #IMPLIED
        comment      CDATA     #IMPLIED
    >
    <!--
        每个衍生类型定义typeDefine中可以定义下列属性
           name        类型名称,在types中唯一
           baseType    基础类型,即此类型实际上就是什么类型,应该是
               FTDStringType或
               FTDNumberType或
               FTDFloatType或
               FTDCharType或
               FTDWordType或
               FTDIntType加上可能的长度说明
           comment     类型说明, 一般用于说明其格式和用途
        如果该类型只有有限的几个允许的取值, 那么就需要定义枚举值enumValue
    -->
    <!ELEMENT enumValue EMPTY>
    <!ATTLIST enumValue
        name       CDATA    #REQUIRED
        comment    CDATA    #IMPLIED
    >
    <!--
        每个枚举值可以定义下列属性
            name       枚举值, 应当符合所属的类型定义
            comment    该枚举值表示的意义
    -->

=== fastquant/ctpdemo/spec/ftd.xml
<?xml version="1.0" encoding="GB2312"?>
<!DOCTYPE FTD SYSTEM "ftd.1.dtd">
<ftd>
    <packages>
        <packageDefine name="Error" tid="TID_Error" model="dialog" comment="错误响应">
            <field name="ErrorField" maxOccur="1" minOccur="1" comment="错误域"/>
            <field name="ErrorTargetSequenceField" maxOccur="1" minOccur="0" comment="错误序列号域"/>
            <field name="ErrorTargetOrderField" maxOccur="1" minOccur="0" comment="错误报单号域"/>
        </packageDefine>
        <packageDefine name="ForceExit" tid="TID_ForceExit" model="none" comment="强制退出">
            <field name="ForceExitField" maxOccur="1" minOccur="1" comment="强制退出域"/>
        </packageDefine>
        <packageDefine name="InstrumentChangeNotify" tid="TID_InstrumentChangeNotify" model="broadcast" comment="合约参数改变通知">
            <field name="InstrumentField" maxOccur="1" minOccur="1" comment="合约域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="InstrumentStatusChangeNotify" tid="TID_InstrumentStatusChangeNotify" model="broadcast" comment="合约状态改变通知">
            <field name="InstrumentStatusField" maxOccur="1" minOccur="1" comment="合约状态域 "/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="MarketBulletin" tid="TID_MarketBulletin" model="broadcast" comment=" 交易所告示广播">
            <field name="BulletinField" maxOccur="1" minOccur="1" comment="告示域"/>
        </packageDefine>
        <packageDefine name="MarketStatusChangeNotify" tid="TID_MarketStatusChangeNotify" model="broadcast" comment="市场状态改变通知">
            <field name="MarketStatusField" maxOccur="1" minOccur="1" comment="市场状态域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="MarketMatchIncData" tid="TID_MarketMatchIncData" model="broadcast" comment="增量成交行情">
            <field name="MarketMatchIncDataField" maxOccur="任意" minOccur="1" comment="增量成交行情域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="MarketMatchData" tid="TID_MarketMatchData" model="broadcast" comment="成交行情">
            <field name="MarketMatchDataField" maxOccur="任意" minOccur="0" comment="成交行情域"/>
            <field name="MarketMatchDataChgField" maxOccur="任意" minOccur="0" comment="成交行情变化域"/>
        </packageDefine>
        <packageDefine name="OrderConfirmation" tid="TID_OrderConfirmation" model="private" comment="报单确认">
            <field name="OrderStatusField" maxOccur="1" minOccur="1" comment="报单状态域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="MarketOrderIncData" tid="TID_MarketOrderIncData" model="broadcast" comment="增量报单行情">
            <field name="MarketOrderDataField" maxOccur="任意" minOccur="1" comment="报单行情域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="ParticipantBulletin" tid="TID_ParticipantBulletin" model="private" comment="会员告示">
            <field name="BulletinField" maxOccur="1" minOccur="1" comment="告示域"/>
        </packageDefine>
        <packageDefine name="ReqOrderAction" tid="TID_OrderAction" model="dialog" comment="报单操作请求">
            <field name="OrderActionField" maxOccur="1" minOccur="1" comment="报单操作域"/>
        </packageDefine>
        <packageDefine name="ReqOrderInsert" tid="TID_OrderInsert" model="dialog" comment="报单录入">
            <field name="OrderInsertField" maxOccur="1" minOccur="1" comment="报单信息域"/>
        </packageDefine>
        <packageDefine name="ReqQryClient" tid="TID_QryClient" model="dialog" comment="客户信息查询">
            <field name="ReqQryClientField" maxOccur="1" minOccur="1" comment="客户查询请求域 "/>
        </packageDefine>
        <packageDefine name="ReqQryDeposit" tid="TID_QryDeposit" model="dialog" comment="会员资金查询">
            <field name="ReqQryDepositField" maxOccur="1" minOccur="1" comment="会员资金查询域"/>
        </packageDefine>
        <packageDefine name="ReqQryInstrument" tid="TID_QryInstrument" model="dialog" comment=" 合约查询">
            <field name="ReqQryInstrumentField" maxOccur="1" minOccur="1" comment="合约查询请 求域"/>
        </packageDefine>
        <packageDefine name="ReqQryInstrumentStatus" tid="TID_QryInstrumentStatus" model="dialog" comment="查询合约交易状态请求">
            <field name="ReqQryInstrumentStatusField" maxOccur="1" minOccur="1" comment="合约状 态查询响应域"/>
        </packageDefine>
        <packageDefine name="ReqQryMarket" tid="TID_QryMarket" model="dialog" comment="市场查 询请求">
            <field name="ReqQryMarketField" maxOccur="1" minOccur="1" comment="市场查询请求 域"/>
        </packageDefine>
        <packageDefine name="ReqQryMarketStatus" tid="TID_QryMarketStatus" model="dialog" comment="查询市场交易状态请求">
            <field name="ReqQryMarketStatusField" maxOccur="1" minOccur="1" comment="市场状态查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryOrder" tid="TID_QryOrder" model="dialog" comment="报单查询">
            <field name="ReqQryOrderField" maxOccur="1" minOccur="1" comment="报单查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryMarketOrderData" tid="TID_QryMarketOrderData" model="dialog" comment="报单行情查询请求">
            <field name="ReqQryMarketOrderDataField" maxOccur="1" minOccur="1" comment="报单行情查询域"/>
        </packageDefine>
        <packageDefine name="ReqQryParticipant" tid="TID_QryParticipant" model="dialog" comment="会员信息查询">
            <field name="ReqQryParticipantField" maxOccur="1" minOccur="1" comment="会员查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryPosition" tid="TID_QryPosition" model="dialog" comment="会员客户持仓查询">
            <field name="ReqQryPositionField" maxOccur="1" minOccur="1" comment="客户持仓查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryPPosition" tid="TID_QryPPosition" model="dialog" comment="会员持仓查询">
            <field name="ReqQryPPositionField" maxOccur="1" minOccur="1" comment="会员持仓查 询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryMarketMatchData" tid="TID_QryMarketMatchData" model="dialog" comment="成交行情查询">
            <field name="ReqQryMarketMatchDataField" maxOccur="1" minOccur="1" comment="成交行情查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryTrade" tid="TID_QryTrade" model="dialog" comment="成交单查询">
            <field name="ReqQryTradeField" maxOccur="1" minOccur="1" comment="成交查询请求域"/>
        </packageDefine>
        <packageDefine name="ReqQryUser" tid="TID_QryUser" model="dialog" comment="查询交易员请求">
            <field name="ReqQryUserField" maxOccur="1" minOccur="1" comment="交易员查询域"/>
        </packageDefine>
        <packageDefine name="ReqQryUserLogin" tid="TID_QryUserLogin" model="dialog" comment="交易员在线查询">
            <field name="ReqQryUserLoginField" maxOccur="1" minOccur="1" comment="交易员在线查询域"/>
        </packageDefine>
        <packageDefine name="ReqUserLogin" tid="TID_UserLogin" model="none" comment="交易员登录请求">
            <field name="ReqUserLoginField" maxOccur="1" minOccur="1" comment="交易员登录请求 域"/>
            <field name="DisseminationstartField" maxOccur="1" minOccur="0" comment="发送信息起始说明域"/>
        </packageDefine>
        <packageDefine name="ReqUserLogout" tid="TID_UserLogout" model="none" comment="交易员登录退出">
            <field name="ReqUserLogoutField" maxOccur="1" minOccur="1" comment="交易员退出登录请求域"/>
        </packageDefine>
        <packageDefine name="ReqUserPasswordUpdate" tid="TID_UserPasswordUpdate" model="dialog" comment="交易员修改密码">
            <field name="ReqUserPasswordUpdateField" maxOccur="1" minOccur="1" comment="交易员修改口令请求域"/>
        </packageDefine>
        <packageDefine name="RspQryUserLogin" tid="TID_QryUserLogin" model="dialog" comment="交易员在线查询应答">
            <field name="UserLoginField" maxOccur="任意" minOccur="1" comment="交易员在线域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspOrderAction" tid="TID_OrderAction" model="dialog" comment="报单操作应答">
            <field name="OrderActionField" maxOccur="1" minOccur="1" comment="报单操作域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspOrderInsert" tid="TID_OrderInsert" model="dialog" comment="报单应答">
            <field name="OrderInsertField" maxOccur="1" minOccur="1" comment="报单信息域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspQryClient" tid="TID_QryClient" model="dialog" comment="客户信息查询应答">
            <field name="ClientField" maxOccur="任意" minOccur="1" comment="客户域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspQryDeposit" tid="TID_QryDeposit" model="dialog" comment="会员资金查询应答">
            <field name="DepositField" maxOccur="任意" minOccur="1" comment="会员资金域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspQryInstrument" tid="TID_QryInstrument" model="dialog" comment="合约查询应答">
            <field name="InstrumentField" maxOccur="任意" minOccur="1" comment="合约域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspQryInstrumentStatus" tid="TID_QryInstrumentStatus" model="dialog" comment="查询合约交易状态应答">
            <field name="InstrumentStatusField" maxOccur="任意" minOccur="1" comment="合约状态域"/>
            <field name="ErrorField" maxOccur="1" minOccur="0" comment="错误域"/>
        </packageDefine>
        <packageDefine name="RspQryMarket" tid="TID_QryMarket" model="dialog" comment="市场查询应答">
